# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - agentpil

on:
  push:
    branches:
      - prisma
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Python dependencies
        run: |
          source venv/bin/activate
          pip install -r src/requirements.txt
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Generate Prisma client
        run: |
          echo "Generating Python Prisma client..."
          source venv/bin/activate
          echo "DATABASE_URL is set: ${DATABASE_URL:0:20}..."
          python -m prisma generate
          echo "Python Prisma client generation completed"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Python dependencies
        run: |
          source venv/bin/activate
          pip install -r src/requirements.txt
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Set up environment variables for Azure
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: Generate Python Prisma client for deployment
        run: |
          echo "Generating Python Prisma client for deployment..."
          source venv/bin/activate
          python -m prisma generate
          echo "Python Prisma client generation completed"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C54250D3D2EF4021BB8AAD8FB19581B9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7AEB074D8A984833B3243965D7350BD4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DA2C071596BE4B0E8613A439B18ADD3F }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'agentpil'
          slot-name: 'Production'


