name: Build and deploy Docker container to Azure Web App

env:
  AZURE_WEBAPP_NAME: agentpil
  REGISTRY: ghcr.io

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Convert repository name to lowercase
    - name: Convert repository name to lowercase
      id: lowercase_repo
      run: |
        LOWERCASE_REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
        echo "lowercase_repo=$LOWERCASE_REPO" >> $GITHUB_OUTPUT
    
    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    # Log in to GitHub Container Registry with personal access token
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # Build and push Docker image
    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.actor }}/${{ github.repository }}:${{ github.ref_name }}
        file: ./Dockerfile
    
    # Display pushed image information
    - name: Display pushed image info
      run: |   
        echo "Pushed images:"
        echo "  ghcr.io/${{ github.actor }}/${{ github.repository }}:${{ github.ref_name }}"
    
    # Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'ghcr.io/${{ github.actor }}/${{ github.repository }}:${{ github.ref_name }}'
